name: Jira Tag Check

on:
  push:
    branches:
      - main

# Failing it again
jobs:
  jira-tag-check:
    uses: Ndomi-Nqeketo/myactions/.github/workflows/action.yml@HAN.v1.0.0

  build:
    needs: jira-tag-check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'