name: Jira Tag Check

on: [push]

jobs:
  call-reusable-workflow:
    uses: Ndomi-Nqeketo/myactions/.github/workflows/action.yml@main

  build:
    needs: call-reusable-workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'