name: Jira Tag Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    #   with:
    #     fetch-depth: 0

    - uses: Ndomi-Nqeketo/myactions/action@SAN
      with:
        token: ${{ secrets.MY_PERSONAL_ACCESS_TOKE }}